# Generated by Django 4.1.4 on 2023-04-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_clothes_delete_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clothes",
            name="image",
            field=models.ImageField(upload_to="clothes_image/"),
        ),
    ]
