# Generated by Django 4.1.4 on 2023-04-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_shoe"),
    ]

    operations = [
        migrations.CreateModel(
            name="accessory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("price", models.FloatField()),
                ("desc", models.CharField(max_length=1500)),
                ("image", models.ImageField(upload_to="accessory_image/")),
            ],
        ),
        migrations.CreateModel(
            name="bag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("price", models.FloatField()),
                ("desc", models.CharField(max_length=1500)),
                ("image", models.ImageField(upload_to="bag_image/")),
            ],
        ),
        migrations.CreateModel(
            name="sunglas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("price", models.FloatField()),
                ("desc", models.CharField(max_length=1500)),
                ("image", models.ImageField(upload_to="sunglas_image/")),
            ],
        ),
        migrations.CreateModel(
            name="wristwatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("price", models.FloatField()),
                ("desc", models.CharField(max_length=1500)),
                ("image", models.ImageField(upload_to="wristwatch_image/")),
            ],
        ),
        migrations.AlterField(
            model_name="shoe",
            name="image",
            field=models.ImageField(upload_to="shoe_image/"),
        ),
    ]
