# Generated by Django 4.1.4 on 2023-04-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_accessory_bag_sunglas_wristwatch_alter_shoe_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="global_brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("brand_name", models.CharField(max_length=30)),
                ("price", models.FloatField()),
                ("desc", models.CharField(max_length=1500)),
                ("image", models.ImageField(upload_to="accessory_image/")),
            ],
        ),
    ]
